version: '3'

services:
  consul-agent-1:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    networks:
    - consul-client-demo
    command: "agent -retry-join $CONSUL_SERVER_HOST -client 0.0.0.0"

networks:
  consul-client-demo:
