version: '3'

services:
  consul-server:
    image: consul:latest
    networks:
      - consul-server-demo
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8302:8302"
      - "8302:8302/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap -ui -advertise=$LOCAL_IP -client 0.0.0.0"

networks:
  consul-server-demo: